version: "3.7"
services:
  app:
    build:
      args:
        user: sergei
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: parser
    container_name: parser-app
    restart: unless-stopped
    working_dir: /var/www/src/public
    volumes:
      - ./:/var/www/
    networks:
      - parser

  db:
    image: mysql:5.7
    container_name: parser-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - parser

  nginx:
    image: nginx:alpine
    container_name: parser-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - parser

networks:
  parser:
    driver: bridge
